### ISSUE TITLE
Implement all APIs for 0.1.0 release

### ISSUE THREAD

**Issue by KeisukeYamashita** [Miro-Ecosystem/go-miro#4]
## What

I need to implement all kinds of PRC described in [Miro REST API](https://developers.miro.com/reference)

## Todo

* [x] Boards
    * [x] Create Board
    * [x] Get Board
    * [x] Share Board
    * [x] Update Board
    * [x] Delete Board
    * [x] Get Current User Boards
* [x] Board User Connections
    * [x] Get Board User Connection
    * [x] Update Board User Connection
    * [x] Delete Board User Connection
* [x] Teams
    * [x] Get Team
    * [x] Update Team
    * [x] List all Team members
    * [x] Get Team Current User Connections
    * [x] Invite to Team
* [x] Team User Connections
    * [x] Get Team User Connection
    * [x] Update Team User Connection
    * [x] Delete Team User Connection
* [x] Pictures
    * [x] Get Picture
    * [x] Create or Update Picture
    * [x] Delete Picture
* [x] User
    * [x] Get User
    * [x] Get Current User
    * [x] Update Current User
* [x] Audit Logs
    * [x] Get logs
* [x] Authorization Info
    * [x] Get Authorization
...
